# 01- NumPy Arrays

In [1]:
# pip install numpy
import numpy as np

In [2]:
list1 = [1,2,3,4,5,6]

In [3]:
arr1 = np.array(list1)

In [4]:
list1

[1, 2, 3, 4, 5, 6]

In [5]:
arr1

array([1, 2, 3, 4, 5, 6])

In [6]:
type (arr1)

numpy.ndarray

In [7]:
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
arr2 = np.array(matrix1)

In [9]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built in methods

In [10]:
range (2,15)

range(2, 15)

In [11]:
list (range (2,15))

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [12]:
np.arange(2,15)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
np.arange(2,15,2)

array([ 2,  4,  6,  8, 10, 12, 14])

In [14]:
np.zeros (3)

array([0., 0., 0.])

In [15]:
np.zeros ((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones (3)

array([1., 1., 1.])

In [17]:
np.ones ((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.eye (3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### linspace

In [19]:
np.linspace (2,5,6)

array([2. , 2.6, 3.2, 3.8, 4.4, 5. ])

In [20]:
np.linspace (2,15,50)

array([ 2.        ,  2.26530612,  2.53061224,  2.79591837,  3.06122449,
        3.32653061,  3.59183673,  3.85714286,  4.12244898,  4.3877551 ,
        4.65306122,  4.91836735,  5.18367347,  5.44897959,  5.71428571,
        5.97959184,  6.24489796,  6.51020408,  6.7755102 ,  7.04081633,
        7.30612245,  7.57142857,  7.83673469,  8.10204082,  8.36734694,
        8.63265306,  8.89795918,  9.16326531,  9.42857143,  9.69387755,
        9.95918367, 10.2244898 , 10.48979592, 10.75510204, 11.02040816,
       11.28571429, 11.55102041, 11.81632653, 12.08163265, 12.34693878,
       12.6122449 , 12.87755102, 13.14285714, 13.40816327, 13.67346939,
       13.93877551, 14.20408163, 14.46938776, 14.73469388, 15.        ])

#### Random

In [21]:
np.random.rand (2)

array([0.02369962, 0.18174535])

In [22]:
np.random.rand (8)

array([0.36234766, 0.72847644, 0.42158821, 0.1069082 , 0.74175446,
       0.89596845, 0.15086584, 0.47413794])

In [23]:
np.random.rand (8,2)

array([[0.7893764 , 0.99251269],
       [0.63369227, 0.61979119],
       [0.06643637, 0.01097316],
       [0.31169802, 0.30224791],
       [0.03047478, 0.16256901],
       [0.41122862, 0.42313448],
       [0.54556309, 0.26426474],
       [0.59670392, 0.65952459]])

In [24]:
# randn
np.random.randn (2)

array([ 0.98975551, -0.37577513])

In [25]:
np.random.randn (2,4)

array([[-1.89516035,  0.27248975,  0.8959415 ,  0.80840361],
       [-0.04700459,  1.11624018, -1.56592972,  1.28119193]])

In [26]:
# randint
np.random.randint (1,100)

67

In [27]:
np.random.randint (1,100,10)

array([53, 35, 57, 60, 33, 87, 83, 27, 14, 31])

In [28]:
np.random.seed (40)
print  (np.random.randint (1,100,10))
print  (np.random.randint (1,100,10))

[71 92  8 38 57 51 66 13 72 20]
[32 75 56 84 60 92 74 97 50 54]


### Array Attributes and Methods

In [29]:
arr1 = np.arange (16)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
arr1.reshape (4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
arr1.reshape (2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [32]:
# arr1.reshape (2,9) => Error 

In [33]:
# arr1.reshape (2,7) Error also

In [34]:
# min ()
arr1.min ()

0

In [35]:
arr2 = np.random.randn (2,5)

In [36]:
arr2

array([[ 1.22856564,  0.39449556, -0.11133525,  0.89847403, -0.52142561],
       [-0.47653982,  1.95110373, -0.58434848,  2.31463471,  0.14793115]])

In [37]:
arr2.min ()

-0.5843484841169373

In [38]:
arr2.max ()

2.314634708294494

In [39]:
# argmin argmax

In [40]:
arr2.argmin ()

7

In [41]:
arr2.argmax ()

8

In [42]:
arr2.shape

(2, 5)

In [43]:
arr2.dtype

dtype('float64')

In [44]:
arr1.dtype

dtype('int32')

### NumPy.sum ()

In [45]:
np.sum(arr1)

120

In [46]:
np.sum(arr2)

5.2415556687144464

In [47]:
sum (arr1)

120

In [48]:
sum(arr2)

array([ 0.75202582,  2.34559929, -0.69568373,  3.21310874, -0.37349446])

In [49]:
## difference between sum and np.sum
%timeit sum (np.arange (200000))
%timeit np.sum (np.arange (200000))

<magic-timeit>:1: RuntimeWarning: overflow encountered in long_scalars


21 ms ± 4.39 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
275 µs ± 35.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [50]:
np.random.randint(5)

1

In [51]:
from numpy.random import randint

In [52]:
randint (100)

43

In [53]:
from numpy import random 

In [54]:
random.randn (4)

array([ 0.0753364 , -0.90983402,  0.96035719, -0.79586382])