# NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange (15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Indexing and Selection with Brackets

In [3]:
arr [5:11]

array([ 5,  6,  7,  8,  9, 10])

In [4]:
arr [0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [5]:
arr [:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr [8:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [7]:
arr [:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Broadcasting

In [9]:
arr [2:6]

array([2, 3, 4, 5])

In [10]:
arr [2:6] = 50

In [11]:
arr

array([ 0,  1, 50, 50, 50, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
arr = np.arange (15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
arr2 = arr [0:7]

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
arr2

array([0, 1, 2, 3, 4, 5, 6])

In [16]:
arr2[:] = 20

In [17]:
arr2

array([20, 20, 20, 20, 20, 20, 20])

In [18]:
arr

array([20, 20, 20, 20, 20, 20, 20,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
arr = np.arange (15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
# copy the original array
arr3 = arr.copy()

In [21]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
arr3 [:] = 200

In [23]:
arr3

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200])

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Indexing 

In [25]:
arr = np.arange (15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
arr[2]

2

In [27]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr_2d[1][2]

6

In [29]:
arr_2d[2][1]

8

In [30]:
arr_2d[2,1]

8

In [31]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr_2d[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [33]:
arr_2d[1:,1:]

array([[5, 6],
       [8, 9]])

#### Boalen Selection

In [34]:
arr5 = np.arange (2,100,3)

In [35]:
arr5

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50,
       53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [36]:
arr5 > 25

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [37]:
arr5 [arr5 > 25]

array([26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68, 71, 74,
       77, 80, 83, 86, 89, 92, 95, 98])

In [38]:
arr5 [(arr5%2) == 0] 

array([ 2,  8, 14, 20, 26, 32, 38, 44, 50, 56, 62, 68, 74, 80, 86, 92, 98])

In [39]:
arr5 [(arr5%2) == 1] 

array([ 5, 11, 17, 23, 29, 35, 41, 47, 53, 59, 65, 71, 77, 83, 89, 95])

In [40]:
boolarr = (arr5%2) == 1

In [41]:
arr5 [boolarr] 

array([ 5, 11, 17, 23, 29, 35, 41, 47, 53, 59, 65, 71, 77, 83, 89, 95])